# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: postgres-commitmaster
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: commitmaster_sirius
      PGDATA: /data/postgres
    volumes:
      - ~/.docker-data/postgres:/data/postgres
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-commitmaster
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-data/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-data/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
